### ISSUE TITLE
Problem with verification of SSL of Nessus API

### ISSUE THREAD

**Issue by bl4ckc00k1e** [ooola/tenable-api#1]
./list-scanners.py
Traceback (most recent call last):
  File "./list-scanners.py", line 14, in <module>
    session = requests.post('https://127.0.0.1:8834/session', data = data)
  File "/usr/lib/python2.7/site-packages/requests/api.py", line 108, in post
    return request('post', url, data=data, json=json, **kwargs)
  File "/usr/lib/python2.7/site-packages/requests/api.py", line 50, in request
    response = session.request(method=method, url=url, **kwargs)
  File "/usr/lib/python2.7/site-packages/requests/sessions.py", line 464, in request
    resp = self.send(prep, **send_kwargs)
  File "/usr/lib/python2.7/site-packages/requests/sessions.py", line 576, in send
    r = adapter.send(request, **kwargs)
  File "/usr/lib/python2.7/site-packages/requests/adapters.py", line 431, in send
    raise SSLError(e, request=request)
**requests.exceptions.SSLError: [SSL: CERTIFICATE_VERIFY_FAILED] certificate verify failed (_ssl.c:579)**

What can i do? thanks

**Comment by bl4ckc00k1e** [comment]
well, with parameter verify=True on header is fixed
